name: CI Back

on:
  push:
    paths:
      - 'back/**'
  pull_request:
    paths:
      - 'back/**'
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build and test
        run: mvn clean verify

      - name: SonarCloud Scan (Back)
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectBaseDir: back
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_BACK }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload JaCoCo report (Back)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-back
          path: back/target/site/jacoco

  docker:
    needs: sonarcloud
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image (Back)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/oc-project-j-back:latest back
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/oc-project-j-back:${SHORT_SHA} back

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image (Back)
        run: docker push -a ${{ secrets.DOCKERHUB_USERNAME }}/oc-project-j-back
