name: CI Front

on:
  push:
    paths:
      - 'front/**'
  pull_request:
    paths:
      - 'front/**'
  workflow_dispatch:

jobs:
  docker:
    needs: sonarcloud
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image (Front)
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/oc-project-j-front:latest front

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push Docker image (Front)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/oc-project-j-front:latest